[project]
name = "end-to-end-data-lake-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mysql-connector-python>=9.2.0",
    "pymongo>=4.11.3",
]
